- title: "A tutorial on Python generators"
  html: "docs-resources/Notebooks/Courses/Solutions/4_Generators-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/4_Generators-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/4_Generators.py"
  name: "4_Generators-sol.qmd"
- title: "An asyncio application"
  py: "docs-resources/Notebooks/Courses/Applications/3_Asynchronous.py"
  name: "3_Asynchronous.qmd"
- title: "Numpy Workout"
  html: "docs-resources/Notebooks/Courses/Solutions/0_Numpy_Workout-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/0_Numpy_Workout-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/0_Numpy_Workout.py"
  name: "0_Numpy_Workout-sol.qmd"
- title: "Scaling App with multiprocessing"
  html: "docs-resources/Notebooks/Courses/Solutions/2_Scaling-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/2_Scaling-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/2_Scaling.py"
  name: "2_Scaling-sol.qmd"
- title: "MultiProcessing, Strong Scaling"
  html: "docs-resources/Notebooks/Courses/Solutions/1_1_MultiProcessing-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/1_1_MultiProcessing-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/1_1_MultiProcessing.py"
  name: "1_1_MultiProcessing-sol.qmd"
- title: "Multiprocessing in Python 3"
  html: "docs-resources/Notebooks/Courses/Solutions/1_0_MultiProcessing_tutorial-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/1_0_MultiProcessing_tutorial-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/1_0_MultiProcessing_tutorial.py"
  name: "1_0_MultiProcessing_tutorial-sol.qmd"
