- title: "Numpy Workout"
  html: "docs-resources/Notebooks/Courses/Solutions/0_Numpy_Workout-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/0_Numpy_Workout-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/0_Numpy_Workout.py"
  name: "0_Numpy_Workout-sol.qmd"
- title: "Mean Pooling"
  py: "docs-resources/Notebooks/Courses/Applications/2_Scaling.py"
  name: "2_Scaling.qmd"
- title: "MultiProcessing, Strong Scaling"
  py: "docs-resources/Notebooks/Courses/Applications/1_MultiProcessing.py"
  name: "1_MultiProcessing.qmd"
- title: "Multiprocessing in Python 3"
  html: "docs-resources/Notebooks/Courses/Solutions/1_MultiProcessing_tutorial-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/1_MultiProcessing_tutorial-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/1_MultiProcessing_tutorial.py"
  name: "1_MultiProcessing_tutorial-sol.qmd"
