- title: "Decorators Tutorial"
  html: "docs-resources/Notebooks/Courses/Solutions/3_1_Decorators_tutorial-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/3_1_Decorators_tutorial-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/3_1_Decorators_tutorial.py"
  name: "3_1_Decorators_tutorial-sol.qmd"
- title: "An asyncio application"
  html: "docs-resources/Notebooks/Courses/Solutions/3_0_Asynchronous-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/3_0_Asynchronous-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/3_0_Asynchronous.py"
  name: "3_0_Asynchronous-sol.qmd"
- title: "Numpy Workout"
  html: "docs-resources/Notebooks/Courses/Solutions/0_Numpy_Workout-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/0_Numpy_Workout-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/0_Numpy_Workout.py"
  name: "0_Numpy_Workout-sol.qmd"
- title: "Distributed models with dask"
  py: "docs-resources/Notebooks/Courses/Applications/5_0_Distributed_models.py"
  name: "5_0_Distributed_models.qmd"
- title: "Scaling App with multiprocessing"
  html: "docs-resources/Notebooks/Courses/Solutions/2_Scaling-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/2_Scaling-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/2_Scaling.py"
  name: "2_Scaling-sol.qmd"
- title: "MultiProcessing, Strong Scaling"
  html: "docs-resources/Notebooks/Courses/Solutions/1_1_MultiProcessing-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/1_1_MultiProcessing-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/1_1_MultiProcessing.py"
  name: "1_1_MultiProcessing-sol.qmd"
- title: "Multiprocessing in Python 3"
  html: "docs-resources/Notebooks/Courses/Solutions/1_0_MultiProcessing_tutorial-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/1_0_MultiProcessing_tutorial-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/1_0_MultiProcessing_tutorial.py"
  name: "1_0_MultiProcessing_tutorial-sol.qmd"
- title: "Dask delayed App"
  py: "docs-resources/Notebooks/Courses/Applications/5_1_Dask_delayed.py"
  name: "5_1_Dask_delayed.qmd"
