- title: "A tutorial on Python generators"
  html: "docs-resources/Notebooks/Courses/Solutions/4_Generators-sol.html"
  ipynb: "docs-resources/Notebooks/Courses/Solutions/4_Generators-sol.ipynb"
  py: "docs-resources/Notebooks/Courses/Applications/4_Generators.py"
  name: "4_Generators-sol.qmd"
- title: "An asyncio application"
  py: "docs-resources/Notebooks/Courses/Applications/3_Asynchronous.py"
  name: "3_Asynchronous.qmd"
